### ISSUE TITLE
Ad insertion into live video stream

### ISSUE THREAD

**Issue by sfahadshahzad** [Eyevinn/channel-engine#1]
Is it possible to generate Playlist on the go while live video source is available when ever we want to switch live source we can switch to.

Just like we normally do in rundown broadcast playout.

We are looking for a solution that can do playout live video source and inject commercials into live stream in user friendly manners.

Regards,

Fahad
Skype :sfahadshahzad

**Comment by birme** [comment]
Hi,

At the moment the Channel Engine only handles VOD as a source but discussions have been had to also be able to handle live HLS manifests as a source. The main challenge there is to find a way to signal that the engine should switch from a live source to a VOD.

However, if I understand your use case correctly what you actually are looking for is a server-side ad-insertion (SSAI) component and that is not the main use case for this engine.

Best regards,
   Jonas
