### ISSUE TITLE
Placement of EXT-X-CUE-IN seems wrong

### ISSUE THREAD

**Issue by birme** [Eyevinn/channel-engine#107]
Though we set `DURATION` on `EXT-X-CUE-OUT` I am not sure if this is critical or a new issue that has been introduced in v3 but interesting to have a look at. When having VOD's with cue markers we get the following in the resulting vod2live stream:

```
https://maitv-vod.lab.eyevinn.technology/VINN.mp4/1000/1000-00012.ts
#EXTINF:1.240,
https://maitv-vod.lab.eyevinn.technology/VINN.mp4/1000/1000-00013.ts
#EXT-X-DISCONTINUITY
#EXTINF:11.000,
https://lab.cdn.eyevinn.technology/THE_GRAND_BUDAPEST_HOTEL_Trailer_2014.mp4/manifest_1_00001.ts
#EXT-X-CUE-IN
```

where the placement of `EXT-X-CUE-IN` looks a bit strange. Maybe it is correct according to the standard but needs to be verified whether it shouldn't be placed before the
```
#EXTINF:11.000,
https://lab.cdn.eyevinn.technology/THE_GRAND_BUDAPEST_HOTEL_Trailer_2014.mp4/manifest_1_00001.ts
```
instead.

**Comment by Nfrederiksen** [comment]
Although it is not a major issue, I believe I have found the source of the strange placement.
