### ISSUE TITLE
Redis performance spikes during VOD change

### ISSUE THREAD

**Issue by dima-ravnur** [Eyevinn/channel-engine#256]
Hello team :)
I performed load tests for channel engine: 
- 500 users and above
- Ramp up period 5 minutes
- Test total duration 10 minutes
- HLS target duration is 6 seconds
- Demuxed audio
- Single instance of Redis of 2 GB size.
- Redis version is 6.0
- Channel configuration:
`const engineOptions = {
  heartbeat: "/",
  channelManager: refChannelManager,
  redisUrl: process.env.Redis__Url,
  useDemuxedAudio: true,
};`

I found that Redis becomes a bottleneck when one VOD is finished and the next one is started:
- Consumes 100% of Redis CPU
- Sometimes consume 100% of Redis memory
- A lot of set requests happens
- A lot of timeouts, 404 and 500 errors returned by service.
- Response time is increased sufficiently and player stuck for a duration of a spike.
- Duration and degree of spikes depends on a number of users and to a duration of a VOD which is loaded next.
- Sometimes I've also seen spikes in the middle of the video though. But they were much smaller.

For 500 users, 3 instances of service and VOD duration 5 min it works in general not bad (have some errors during spikes though). But below is example of 1000 users for scaled system with 10 instances of a service (to ensure there is no CPU issues and understand how much Redis can handle).
![image](https://github.com/Eyevinn/channel-engine/assets/73594896/e2703455-6d05-41b7-a272-04e5d6221008)

Below are examples of what happens with Redis during such spikes:

1. High CPU + average Memory + A lot of Sets operations
2. High CPU + High Memory + few set operations

![image](https://github.com/Eyevinn/channel-engine/assets/73594896/f67fce60-8961-460f-b15b-7c060d02295e)
![image](https://github.com/Eyevinn/channel-engine/assets/73594896/50fe0558-c5c6-40b4-a4de-0e8e03f78a65)
![image](https://github.com/Eyevinn/channel-engine/assets/73594896/02c5ea8f-ac39-448c-8de1-e6a70f7b6eff)

According to those images you can find that we should keep a lot of spare Redis resources to be able to survive spikes while most of time we don't need those.

Also attaching some logs (there are many errors in logs during those spikes).
[channel-eyevinn-error-logs.txt](https://github.com/Eyevinn/channel-engine/files/11440339/channel-eyevinn-error-logs.txt)

I didn't investigate the code deeply. But from what I see it makes me think that during next VOD loading all income request somehow participate in that update (according to a number of set requests in Redis) or maybe fight for some shared resource in Redis. I remember we had such issue for cached data when multiple read request start simultaneously loading cache data after the cache invalidation.

**Comment by birme** [comment]
Hi!
Thank you for a very detailed analysis. Much appreciated. What version of the Redis engine are you using?

**Comment by birme** [comment]
And just as a note (and not to diminish this problem), it is common (and also recommended) to put an origin shield between the engine and the end user player.

**Comment by birme** [comment]
We have done some optimization regarding the amount of data serialized and stored in the Redis DB. Available from v4.3.0. Happy if you could try it out and see if this gives some performance improvements.

**Comment by birme** [comment]
We have done even further improvements on this in v4.3.3: https://github.com/Eyevinn/channel-engine/releases/tag/v4.3.3
