### ISSUE TITLE
Feeds go to slate after one day (or end of feed)

### ISSUE THREAD

**Issue by bcorvino** [Eyevinn/channel-engine#26]
Hi,

I've been working with the channel-engine to implement a vod-to-live service for our website.  It seems like when the the channel-engine reaches the end of the feed, though, it just goes to slate and doesn't seem to be able to recover or loop.   This is also true after I implemented a "schedule" which basically loops the vod library until it reaches 24 hours.  In this case, the channel engine seems to go to slate after 24 hours.  

Is there a flag for looping content, or some other method?  Any help would be greatly appreciated.

Thank you!

**Comment by birme** [comment]
The Channel Engine in itself does not have any real notion of a schedule in that sense so it is up to the implementation of the getNextVod callback to handle this. What is your asset manager implementation looking like?
