### ISSUE TITLE
Issue seems like http://lambda.eyevinn.technology/stitch/master.m3u8 is not working

### ISSUE THREAD

**Issue by Gizmeondevwip** [Eyevinn/channel-engine#303]
![image](https://github.com/Eyevinn/channel-engine/assets/59248412/c311ec6c-2ee5-42fe-899c-2424387f12be)
![image](https://github.com/Eyevinn/channel-engine/assets/59248412/57cc35d4-f604-4778-b80b-12910ce8fa25)

**Comment by birme** [comment]
Hi, we have taken down this lambda stitch function as it was potentially abused.
You can spin it up yourselves as code is available here: https://github.com/Eyevinn/lambda-stitch
Another option is to use our hosted version if you just want to try this out, see https://osaas-api.docs.eyevinn.technology/services/channel-engine.html

**Comment by Gizmeondevwip** [comment]
Hi is this was taken down recently?

**Comment by birme** [comment]
Yes, relatively

**Comment by Gizmeondevwip** [comment]
This has worked. Thankyou
