### ISSUE TITLE
Support for subtitles

### ISSUE THREAD

**Issue by birme** [Eyevinn/channel-engine#44]
- Slice the webvtt media playlist into media sequences aligned with video. 
- Update master manifest response with “virtual” subtitle tracks referenced. Requires to define a predefined set of languages per channel
- Match available subtitle tracks in VOD with the predefined set of languages per channel. And provide empty / “black” for those tracks without a match
- Provide a subtitle playlist endpoint that is aligned with the media sequence of video

**Comment by birme** [comment]
Depends on https://github.com/Eyevinn/hls-vodtolive/issues/50

**Comment by Ronileco** [comment]
Hi @birme - looks awesome!

What about the x-timestamp-map on the vtt file?
Isn't it needed for the subs to work properly during the live stream?
